# Generated by Django 2.2.24 on 2021-07-07 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='stories')),
                ('story', models.TextField()),
                ('post_date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_liked', models.DateTimeField(auto_now=True)),
                ('story_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_liked', to='App_main.Story')),
                ('user_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_commented', models.DateTimeField(auto_now=True)),
                ('story_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_commented', to='App_main.Story')),
                ('user_commented', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_commented', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
