# Generated by Django 2.2.24 on 2021-07-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_likes_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='like',
        ),
    ]
