# Generated by Django 2.2.24 on 2021-07-08 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0003_remove_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='story_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_commented', to='App_main.Story'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='story_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_liked', to='App_main.Story'),
        ),
    ]
